<section class="about">
    <h2> ABOUT </h2>
  <h3> Ils sont entrés dans la légende</h3>
  <article class="cards">
    <div class="card" style="width: 18rem;">
      <img src="https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Lucian_0.jpg" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Eloan le mage noir</h5>
        <p class="card-text">J'ai adoré le projet de A a Z !</p>
      </div>
    </div>
    
    <div class="card" style="width: 18rem;">
      <img src="https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Lux_0.jpg" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Emilie la délégué</h5>
        <p class="card-text">Ce que j'ai préféré c'était le php poo oriented object pour les nuls</p>
      </div>
    </div>
    
    <div class="card" style="width: 18rem;">
      <img src="https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Gragas_0.jpg" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Antoine cerveau en bouillie</h5>
        <p class="card-text">Please send help</p>
      </div>
    </div>
  </article>
</section>