<?php

foreach ($categories_array as $category) {
?>
    <h3><?= $category->getName() ?></h3>
    <ul>
        <?php

        $AllChannelsFromCategory = $instanceCategoryManager->getAllChannelsFromCategory($category->getId());

        if (isset($AllChannelsFromCategory)) {

            foreach ($AllChannelsFromCategory as $channel) {; ?>

                <li>
                    <?= $channel->getName() ?>
                    <a href='index.php?id_channel=<?= $channel->getId() ?>'>Lire</a>
                </li>

                <ul>
                    <li>

                    </li>
                </ul>

        <?php }
        }; ?>

    </ul>
    </br>
<?php
}
?>

<div class="container mt-5">
    <form method="POST" action="index.php?route=create-category">
        <div class="form-group">
            <label for="name">Nom de la catégorie :</label>
            <input type="text" class="form-control" id="name" name="name" placeholder="Entrez le nom de la catégorie">
        </div>
        <button type="submit" class="btn btn-primary">Soumettre</button>
    </form>
</div>
<div class="container mt-5">
    <form method="POST" action="index.php?route=create-channel">
        <div class="form-group">
            <label for="name">Nom du channel :</label>
            <input type="hidden" name="id_category" value="5" />
            <input type="text" class="form-control" id="name" name="name" placeholder="Entrez le nom du channel">
        </div>
        <button type="submit" class="btn btn-primary">Soumettre</button>
    </form>
</div>
<div class="container mt-5">
    <form method="POST" action="index.php?route=delete-channel&id_cat=3">
        <div class="form-group">
            <label for="name">Supprimer le salon</label>
            <input type="hidden" name="id_category" value="5" />
            <input type="text" class="form-control" id="name" name="name" placeholder="Entrez le nom du channel">
        </div>
        <button type="submit" class="btn btn-primary">Supprimer</button>
    </form>
</div>

<?php


$instancePostManager = new PostManager();
$postToDisplay = $instancePostManager->findAll();
$instanceChannelController = new ChannelController();
$channelsToDisplay = $instanceChannelController->showChannels();
foreach ($channelsToDisplay as $channel) {
?>
    <a href="index.php?route=delete-channel&channel-id=3">DELETE Channel</a>
    <a href="index.php?route=delete-category&category-id=2">DELETE category</a>
    <p><?= $channel->getName() ?> in <?= $channel->getCategory()->getName() ?></p>
    </br>
<?php
}

foreach ($postToDisplay as $post) {
?>
    <div class="card mb-3">
        <div class="card-header">
            <strong>Channel:</strong> <?php echo $post->getChannel()->getName(); ?>
            <br>
            <strong>Category:</strong> <?php echo $post->getChannel()->getCategory()->getName(); ?>
        </div>
        <div class="card-body">
            <p class="card-text"><?php echo $post->getContent(); ?></p>
        </div>
    </div>
<?php
}
?>
<div class="container mt-5">
    <form method="POST" action="index.php?route=create-post">
        <div class="form-group">
            <input type="hidden" name="id_channel" value="6" />
            <label for="content">Commentaire :</label>
            <textarea class="form-control" id="content" name="content" rows="4" placeholder="Saisissez votre commentaire ici"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Envoyer</button>
    </form>
</div>