<?php


?>
<div class="container mt-5">
    <form method="POST" action="index.php?route=create-category">
        <div class="form-group">
            <label for="name">Nom de la catégorie :</label>
            <input type="text" class="form-control" id="name" name="name" placeholder="Entrez le nom de la catégorie">
        </div>
        <button type="submit" class="btn btn-primary">+</button>
    </form>
</div>

<?php
foreach ($categories_array as $category) {
    $categoryName = $category->getName();
    $categoryChannels = $category->getChannels();
?>
    <h2 style="color: red;"><?= $categoryName ?></h2>
    <div class="container mt-5">
        <form method="POST" action="index.php?route=create-channel">
            <div class="form-group">
                <label for="name">Nouveau salon</label>
                <input type="hidden" name="id_category" value="<?= $category->getId() ?>" />
                <input type="text" class="form-control" id="name" name="name" placeholder="Entrez le nom du channel">
            </div>
            <button type="submit" class="btn btn-primary">+</button>
        </form>
    </div>
    <a href="index.php?route=delete-category&category-id=<?= $category->getId() ?>">DELETE category</a>

    <?php
    if (isset($categoryChannels)) {
        foreach ($categoryChannels as $channel) {
            $channelName = $channel->getName();
            $channelPosts = $channel->getPosts();
    ?>
            <h3 style="color: green;"><?= $channelName ?></h3>
            <div class="container mt-5">
                <form method="POST" action="index.php?route=create-post">
                    <div class="form-group">
                        <input type="hidden" name="id_channel" value="<?= $channel->getId() ?>" />
                        <label for="content">Add post</label>
                        <textarea class="form-control" id="content" name="content" rows="4" placeholder="Saisissez votre commentaire ici"></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary">+</button>
                </form>
            </div>
            <a href="index.php?route=delete-channel&channel-id=<?= $channel->getId() ?>">DELETE Channel</a>

            <?php
            if (isset($channelPosts)) {
                foreach ($channelPosts as $post) {
                    $postContent = $post->getContent();
                    $postDate = $post->getCreatedAt();
                    $post_Id = $post->getId();
            ?>
                    <a href="index.php?route=delete-post&post-id=<?= $post_Id ?>">DELETE</a>
                    <p style="color: purple;"><?= $postContent ?></p>
                    <p style="font-style: italic;"><?= $postDate ?></p>

<?php
                }
            }
        }
    }
}
?>