<?php 
$instancePostManager = new PostManager();
$postToDisplay = $instancePostManager->findAll();
foreach ($postToDisplay as $post) {
?>

    <div class="card" style="width: 18rem;">
  <img src="https://source.unsplash.com/random" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title"><?= $post->getId() ?></h5>
    <p class="card-text"><?= $post->getContent() ?></p>
  </div>
</div>
<?php
}
?>