<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="styles.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
  <title>Distorsion</title>
</head>
<body>

    <header class="header">
        <figure class="logo">
          <h1>Distorsion</h1>
          <img><i class="fa-solid fa-tornado fa-shake"></i></img>
        </figure>
        
        <nav class="nav">
          <a href="#">Chat</a>
          <a href="#">À propos</a>
        </nav>
    </header>

    <main>
        <section class="left-column">
            <?php
            foreach ($categories_array as $keyCat => $category) {
                $categoryName = $category->getName();
                $categoryChannels = $category->getChannels()
                ?> <h2><?=$categoryName?></h2>
                <?php
                if (isset($categoryChannels)) {
                    foreach($categoryChannels as $keyChan => $channel) {
                        $channelName = $channel->getName();
                        $channelPosts = $channel->getPosts();
                        ?> <a href="index.php?id_channel=<?= $keyChan?>&id_category=<?=$keyCat?>"><?=$channelName?></a>
                        <?php
                    }
                }
            }
            ?>
        </section>
        
        
        <section class="chat-space">
            <div>
                <p class=post-content>Messages</p>
                <?php 
                    if(isset($_GET["id_channel"])&& isset($_GET["id_category"])) {
                        $channelsSelected = $categories_array[$_GET["id_category"]]->getChannels();
                        if (isset($channelsSelected)) {
                            $postToDisplay = $channelsSelected[$_GET["id_channel"]]->getPosts();
                            foreach($postToDisplay as $post) {
                            ?>
                                <p><?= $post->getContent();?></p>
                                <?php
                            }
                        }
                    } 
                ?>
            </div>

            <form class="post-form" method = "post" action="index.php?route=create-post">
                <input type="hidden" name="id_channel" value="6" />
                <label for="content">Message:</label>
                <textarea id="content" name="content"></textarea>
                <button type="submit">Envoyer</button>
            </form>
          
        </section>
          
    </main>

</body>
</html>
