<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="styles.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
  <title>Distorsion</title>
</head>
<body>

    <header class="header">
        <figure class="logo">
          <h1>Distorsion</h1>
          <img><i class="fa-solid fa-tornado"></i></img>
        </figure>
        
        <nav class="nav">
          <a href="#">Chat</a>
          <a href="#">À propos</a>
        </nav>
    </header>

    <main>
        <session class="left-column">
              <h2>Nom catégorie</h2>
                  <h3>Nom salon</h3>
        </session>
        
        
        <session class="chat-space">
            <div>
                <p class=post-content>Messages</p>
            </div>

            <form class="post-form" method = "post" action="">
                <label for="post">Message:</label>
                <textarea id="post" name="post"></textarea>
                <button type="submit">Envoyer</button>
            </form>
          
        </session>
          
    </main>

</body>
</html>
